version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directories:
      - /
      - /tools
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"
