// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: packetbroker/api/v3/enums.proto

package packetbroker

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LoRaWAN region as defined in Regional Parameters.
type Region int32

const (
	Region_UNKNOWN_REGION Region = 0
	Region_EU_863_870     Region = 1
	Region_US_902_928     Region = 2
	Region_CN_779_787     Region = 3
	Region_EU_433         Region = 4
	Region_AU_915_928     Region = 5
	Region_CN_470_510     Region = 6
	Region_AS_923         Region = 7
	// AS923 group 1
	Region_AS_923_1 Region = 11
	// AS923 group 2
	Region_AS_923_2 Region = 12
	// AS923 group 3
	Region_AS_923_3   Region = 13
	Region_KR_920_923 Region = 8
	Region_IN_865_867 Region = 9
	Region_RU_864_870 Region = 10
	// LoRa 2.4 GHz
	Region_WW_2G4 Region = 14
)

var Region_name = map[int32]string{
	0:  "UNKNOWN_REGION",
	1:  "EU_863_870",
	2:  "US_902_928",
	3:  "CN_779_787",
	4:  "EU_433",
	5:  "AU_915_928",
	6:  "CN_470_510",
	7:  "AS_923",
	11: "AS_923_1",
	12: "AS_923_2",
	13: "AS_923_3",
	8:  "KR_920_923",
	9:  "IN_865_867",
	10: "RU_864_870",
	14: "WW_2G4",
}

var Region_value = map[string]int32{
	"UNKNOWN_REGION": 0,
	"EU_863_870":     1,
	"US_902_928":     2,
	"CN_779_787":     3,
	"EU_433":         4,
	"AU_915_928":     5,
	"CN_470_510":     6,
	"AS_923":         7,
	"AS_923_1":       11,
	"AS_923_2":       12,
	"AS_923_3":       13,
	"KR_920_923":     8,
	"IN_865_867":     9,
	"RU_864_870":     10,
	"WW_2G4":         14,
}

func (Region) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{0}
}

// LoRaWAN class for transmitting downlink.
type DownlinkMessageClass int32

const (
	DownlinkMessageClass_CLASS_A DownlinkMessageClass = 0
	DownlinkMessageClass_CLASS_B DownlinkMessageClass = 1
	DownlinkMessageClass_CLASS_C DownlinkMessageClass = 2
)

var DownlinkMessageClass_name = map[int32]string{
	0: "CLASS_A",
	1: "CLASS_B",
	2: "CLASS_C",
}

var DownlinkMessageClass_value = map[string]int32{
	"CLASS_A": 0,
	"CLASS_B": 1,
	"CLASS_C": 2,
}

func (DownlinkMessageClass) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{1}
}

// Priority of a downlink message.
type DownlinkMessagePriority int32

const (
	// Lowest priority.
	DownlinkMessagePriority_LOWEST DownlinkMessagePriority = 0
	// Low priority.
	DownlinkMessagePriority_LOW DownlinkMessagePriority = 1
	// Normal priority.
	DownlinkMessagePriority_NORMAL DownlinkMessagePriority = 2
	// High priority.
	// Sets the HiPriority flag in the LoRaWAN Backend Interfaces XmitDataReq message.
	DownlinkMessagePriority_HIGH DownlinkMessagePriority = 3
	// Highest priority.
	// Sets the HiPriority flag in the LoRaWAN Backend Interfaces XmitDataReq message.
	DownlinkMessagePriority_HIGHEST DownlinkMessagePriority = 4
)

var DownlinkMessagePriority_name = map[int32]string{
	0: "LOWEST",
	1: "LOW",
	2: "NORMAL",
	3: "HIGH",
	4: "HIGHEST",
}

var DownlinkMessagePriority_value = map[string]int32{
	"LOWEST":  0,
	"LOW":     1,
	"NORMAL":  2,
	"HIGH":    3,
	"HIGHEST": 4,
}

func (DownlinkMessagePriority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{2}
}

type MessageDeliveryState int32

const (
	// The message has been accepted for forwarding or delivery.
	MessageDeliveryState_ACCEPTED MessageDeliveryState = 0
	// The message has been forwarded to another host for delivery.
	MessageDeliveryState_FORWARDED MessageDeliveryState = 1
	// The message has been delivered to the receiver.
	MessageDeliveryState_DELIVERED MessageDeliveryState = 2
	// The message has been processed by the receiver.
	MessageDeliveryState_PROCESSED MessageDeliveryState = 3
)

var MessageDeliveryState_name = map[int32]string{
	0: "ACCEPTED",
	1: "FORWARDED",
	2: "DELIVERED",
	3: "PROCESSED",
}

var MessageDeliveryState_value = map[string]int32{
	"ACCEPTED":  0,
	"FORWARDED": 1,
	"DELIVERED": 2,
	"PROCESSED": 3,
}

func (MessageDeliveryState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{3}
}

type UplinkMessageProcessingError int32

const (
	UplinkMessageProcessingError_UPLINK_UNKNOWN_ERROR UplinkMessageProcessingError = 0
	// The message does not pass the routing policy.
	UplinkMessageProcessingError_UPLINK_ROUTING_POLICY UplinkMessageProcessingError = 1
	// A matching device session could not be found.
	// This can be caused by an unknown DevAddr or a MIC check failure.
	UplinkMessageProcessingError_MATCH_SESSION UplinkMessageProcessingError = 2
	// Internal error.
	UplinkMessageProcessingError_UPLINK_INTERNAL UplinkMessageProcessingError = 3
	// No Home Network endpoints found.
	UplinkMessageProcessingError_NO_HOME_NETWORK_ENDPOINTS UplinkMessageProcessingError = 4
)

var UplinkMessageProcessingError_name = map[int32]string{
	0: "UPLINK_UNKNOWN_ERROR",
	1: "UPLINK_ROUTING_POLICY",
	2: "MATCH_SESSION",
	3: "UPLINK_INTERNAL",
	4: "NO_HOME_NETWORK_ENDPOINTS",
}

var UplinkMessageProcessingError_value = map[string]int32{
	"UPLINK_UNKNOWN_ERROR":      0,
	"UPLINK_ROUTING_POLICY":     1,
	"MATCH_SESSION":             2,
	"UPLINK_INTERNAL":           3,
	"NO_HOME_NETWORK_ENDPOINTS": 4,
}

func (UplinkMessageProcessingError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{4}
}

type DownlinkMessageProcessingError int32

const (
	DownlinkMessageProcessingError_DOWNLINK_UNKNOWN_ERROR DownlinkMessageProcessingError = 0
	// The packet was sent too late for transmission, i.e. the window closed.
	DownlinkMessageProcessingError_TOO_LATE DownlinkMessageProcessingError = 1
	// The packet was sent too early for transmission, i.e. the transmission time is too far in the future.
	DownlinkMessageProcessingError_TOO_EARLY DownlinkMessageProcessingError = 2
	// There was a collision with another packet.
	DownlinkMessageProcessingError_COLLISION_PACKET DownlinkMessageProcessingError = 3
	// There was a collision with the class B beacon.
	DownlinkMessageProcessingError_COLLISION_BEACON DownlinkMessageProcessingError = 4
	// Wrong frequency.
	DownlinkMessageProcessingError_TX_FREQUENCY DownlinkMessageProcessingError = 5
	// Wrong TX power.
	DownlinkMessageProcessingError_TX_POWER DownlinkMessageProcessingError = 6
	// No GPS lock while the transmission requires an absolute time.
	DownlinkMessageProcessingError_GPS_UNLOCKED DownlinkMessageProcessingError = 7
	// The message does not pass the routing policy.
	DownlinkMessageProcessingError_DOWNLINK_ROUTING_POLICY DownlinkMessageProcessingError = 8
	// Internal error.
	DownlinkMessageProcessingError_DOWNLINK_INTERNAL DownlinkMessageProcessingError = 9
)

var DownlinkMessageProcessingError_name = map[int32]string{
	0: "DOWNLINK_UNKNOWN_ERROR",
	1: "TOO_LATE",
	2: "TOO_EARLY",
	3: "COLLISION_PACKET",
	4: "COLLISION_BEACON",
	5: "TX_FREQUENCY",
	6: "TX_POWER",
	7: "GPS_UNLOCKED",
	8: "DOWNLINK_ROUTING_POLICY",
	9: "DOWNLINK_INTERNAL",
}

var DownlinkMessageProcessingError_value = map[string]int32{
	"DOWNLINK_UNKNOWN_ERROR":  0,
	"TOO_LATE":                1,
	"TOO_EARLY":               2,
	"COLLISION_PACKET":        3,
	"COLLISION_BEACON":        4,
	"TX_FREQUENCY":            5,
	"TX_POWER":                6,
	"GPS_UNLOCKED":            7,
	"DOWNLINK_ROUTING_POLICY": 8,
	"DOWNLINK_INTERNAL":       9,
}

func (DownlinkMessageProcessingError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{5}
}

type TerrestrialAntennaPlacement int32

const (
	// Unknown antenna placement.
	TerrestrialAntennaPlacement_UNKNOWN_PLACEMENT TerrestrialAntennaPlacement = 0
	// Indoor antenna placement.
	TerrestrialAntennaPlacement_INDOOR TerrestrialAntennaPlacement = 1
	// Outdoor antenna placement.
	TerrestrialAntennaPlacement_OUTDOOR TerrestrialAntennaPlacement = 2
)

var TerrestrialAntennaPlacement_name = map[int32]string{
	0: "UNKNOWN_PLACEMENT",
	1: "INDOOR",
	2: "OUTDOOR",
}

var TerrestrialAntennaPlacement_value = map[string]int32{
	"UNKNOWN_PLACEMENT": 0,
	"INDOOR":            1,
	"OUTDOOR":           2,
}

func (TerrestrialAntennaPlacement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{6}
}

type Modulation int32

const (
	// LoRa modulation.
	Modulation_LORA Modulation = 0
	// FSK modulation.
	Modulation_FSK Modulation = 1
)

var Modulation_name = map[int32]string{
	0: "LORA",
	1: "FSK",
}

var Modulation_value = map[string]int32{
	"LORA": 0,
	"FSK":  1,
}

func (Modulation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{7}
}

type Right int32

const (
	// Right to list networks and get network information.
	Right_READ_NETWORK Right = 0
	// Right to read contact information of networks.
	Right_READ_NETWORK_CONTACT Right = 1
	// Right to list the route table.
	Right_READ_ROUTE_TABLE Right = 5
	// Right to read target authentication information.
	Right_READ_TARGET_AUTH Right = 6
	// Right to read and list routing policies.
	Right_READ_ROUTING_POLICY Right = 4
	// Right to write routing policies.
	Right_WRITE_ROUTING_POLICY Right = 7
	// Right to read and list gateway visibilities.
	Right_READ_GATEWAY_VISIBILITY Right = 8
	// Right to write gateway visibilities.
	Right_WRITE_GATEWAY_VISIBILITY Right = 9
	// Right to read traffic.
	Right_READ_TRAFFIC Right = 10
	// Right to write traffic.
	Right_WRITE_TRAFFIC Right = 11
)

var Right_name = map[int32]string{
	0:  "READ_NETWORK",
	1:  "READ_NETWORK_CONTACT",
	5:  "READ_ROUTE_TABLE",
	6:  "READ_TARGET_AUTH",
	4:  "READ_ROUTING_POLICY",
	7:  "WRITE_ROUTING_POLICY",
	8:  "READ_GATEWAY_VISIBILITY",
	9:  "WRITE_GATEWAY_VISIBILITY",
	10: "READ_TRAFFIC",
	11: "WRITE_TRAFFIC",
}

var Right_value = map[string]int32{
	"READ_NETWORK":             0,
	"READ_NETWORK_CONTACT":     1,
	"READ_ROUTE_TABLE":         5,
	"READ_TARGET_AUTH":         6,
	"READ_ROUTING_POLICY":      4,
	"WRITE_ROUTING_POLICY":     7,
	"READ_GATEWAY_VISIBILITY":  8,
	"WRITE_GATEWAY_VISIBILITY": 9,
	"READ_TRAFFIC":             10,
	"WRITE_TRAFFIC":            11,
}

func (Right) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{8}
}

type APIKeyState int32

const (
	// Requested.
	APIKeyState_REQUESTED APIKeyState = 0
	// Approved.
	APIKeyState_APPROVED APIKeyState = 1
	// Rejected.
	APIKeyState_REJECTED APIKeyState = 2
)

var APIKeyState_name = map[int32]string{
	0: "REQUESTED",
	1: "APPROVED",
	2: "REJECTED",
}

var APIKeyState_value = map[string]int32{
	"REQUESTED": 0,
	"APPROVED":  1,
	"REJECTED":  2,
}

func (APIKeyState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{9}
}

type TargetProtocol int32

const (
	// LoRaWAN Backend Interfaces (TS002) 1.0.
	TargetProtocol_TS002_V1_0 TargetProtocol = 0
	// LoRaWAN Backend Interfaces (TS002) 1.1.0.
	TargetProtocol_TS002_V1_1_0 TargetProtocol = 1
)

var TargetProtocol_name = map[int32]string{
	0: "TS002_V1_0",
	1: "TS002_V1_1_0",
}

var TargetProtocol_value = map[string]int32{
	"TS002_V1_0":   0,
	"TS002_V1_1_0": 1,
}

func (TargetProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{10}
}

type RegionalParametersVersion int32

const (
	// LoRaWAN 1.0.
	RegionalParametersVersion_TS001_V1_0 RegionalParametersVersion = 0
	// LoRaWAN 1.0.1.
	RegionalParametersVersion_TS001_V1_0_1 RegionalParametersVersion = 1
	// LoRaWAN Regional Parameters 1.0.2.
	RegionalParametersVersion_RP001_V1_0_2_A RegionalParametersVersion = 2
	// LoRaWAN Regional Parameters 1.0.2 revision B.
	RegionalParametersVersion_RP001_V1_0_2_B RegionalParametersVersion = 3
	// LoRaWAN Regional Parameters 1.0.3 revision A.
	RegionalParametersVersion_RP001_V1_0_3_A RegionalParametersVersion = 4
	// LoRaWAN Regional Parameters 1.1 revision A.
	RegionalParametersVersion_RP001_V1_1_A RegionalParametersVersion = 5
	// LoRaWAN Regional Parameters 1.1 revision B.
	RegionalParametersVersion_RP001_V1_1_B RegionalParametersVersion = 6
	// LoRaWAN Regional Parameters RP002-1.0.0.
	RegionalParametersVersion_RP002_V1_0_0 RegionalParametersVersion = 7
	// LoRaWAN Regional Parameters RP002-1.0.1.
	RegionalParametersVersion_RP002_V1_0_1 RegionalParametersVersion = 8
	// LoRaWAN Regional Parameters RP002-1.0.2.
	RegionalParametersVersion_RP002_V1_0_2 RegionalParametersVersion = 9
	// LoRaWAN Regional Parameters RP002-1.0.3.
	RegionalParametersVersion_RP002_V1_0_3 RegionalParametersVersion = 10
)

var RegionalParametersVersion_name = map[int32]string{
	0:  "TS001_V1_0",
	1:  "TS001_V1_0_1",
	2:  "RP001_V1_0_2_A",
	3:  "RP001_V1_0_2_B",
	4:  "RP001_V1_0_3_A",
	5:  "RP001_V1_1_A",
	6:  "RP001_V1_1_B",
	7:  "RP002_V1_0_0",
	8:  "RP002_V1_0_1",
	9:  "RP002_V1_0_2",
	10: "RP002_V1_0_3",
}

var RegionalParametersVersion_value = map[string]int32{
	"TS001_V1_0":     0,
	"TS001_V1_0_1":   1,
	"RP001_V1_0_2_A": 2,
	"RP001_V1_0_2_B": 3,
	"RP001_V1_0_3_A": 4,
	"RP001_V1_1_A":   5,
	"RP001_V1_1_B":   6,
	"RP002_V1_0_0":   7,
	"RP002_V1_0_1":   8,
	"RP002_V1_0_2":   9,
	"RP002_V1_0_3":   10,
}

func (RegionalParametersVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{11}
}

type RegionalParametersVersionValue struct {
	Value                RegionalParametersVersion `protobuf:"varint,1,opt,name=value,proto3,enum=org.packetbroker.v3.RegionalParametersVersion" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RegionalParametersVersionValue) Reset()      { *m = RegionalParametersVersionValue{} }
func (*RegionalParametersVersionValue) ProtoMessage() {}
func (*RegionalParametersVersionValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_09f966b65c116bd0, []int{0}
}
func (m *RegionalParametersVersionValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegionalParametersVersionValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegionalParametersVersionValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegionalParametersVersionValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionalParametersVersionValue.Merge(m, src)
}
func (m *RegionalParametersVersionValue) XXX_Size() int {
	return m.Size()
}
func (m *RegionalParametersVersionValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionalParametersVersionValue.DiscardUnknown(m)
}

var xxx_messageInfo_RegionalParametersVersionValue proto.InternalMessageInfo

func (m *RegionalParametersVersionValue) GetValue() RegionalParametersVersion {
	if m != nil {
		return m.Value
	}
	return RegionalParametersVersion_TS001_V1_0
}

func init() {
	proto.RegisterEnum("org.packetbroker.v3.Region", Region_name, Region_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.Region", Region_name, Region_value)
	proto.RegisterEnum("org.packetbroker.v3.DownlinkMessageClass", DownlinkMessageClass_name, DownlinkMessageClass_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.DownlinkMessageClass", DownlinkMessageClass_name, DownlinkMessageClass_value)
	proto.RegisterEnum("org.packetbroker.v3.DownlinkMessagePriority", DownlinkMessagePriority_name, DownlinkMessagePriority_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.DownlinkMessagePriority", DownlinkMessagePriority_name, DownlinkMessagePriority_value)
	proto.RegisterEnum("org.packetbroker.v3.MessageDeliveryState", MessageDeliveryState_name, MessageDeliveryState_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.MessageDeliveryState", MessageDeliveryState_name, MessageDeliveryState_value)
	proto.RegisterEnum("org.packetbroker.v3.UplinkMessageProcessingError", UplinkMessageProcessingError_name, UplinkMessageProcessingError_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.UplinkMessageProcessingError", UplinkMessageProcessingError_name, UplinkMessageProcessingError_value)
	proto.RegisterEnum("org.packetbroker.v3.DownlinkMessageProcessingError", DownlinkMessageProcessingError_name, DownlinkMessageProcessingError_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.DownlinkMessageProcessingError", DownlinkMessageProcessingError_name, DownlinkMessageProcessingError_value)
	proto.RegisterEnum("org.packetbroker.v3.TerrestrialAntennaPlacement", TerrestrialAntennaPlacement_name, TerrestrialAntennaPlacement_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.TerrestrialAntennaPlacement", TerrestrialAntennaPlacement_name, TerrestrialAntennaPlacement_value)
	proto.RegisterEnum("org.packetbroker.v3.Modulation", Modulation_name, Modulation_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.Modulation", Modulation_name, Modulation_value)
	proto.RegisterEnum("org.packetbroker.v3.Right", Right_name, Right_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.Right", Right_name, Right_value)
	proto.RegisterEnum("org.packetbroker.v3.APIKeyState", APIKeyState_name, APIKeyState_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.APIKeyState", APIKeyState_name, APIKeyState_value)
	proto.RegisterEnum("org.packetbroker.v3.TargetProtocol", TargetProtocol_name, TargetProtocol_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.TargetProtocol", TargetProtocol_name, TargetProtocol_value)
	proto.RegisterEnum("org.packetbroker.v3.RegionalParametersVersion", RegionalParametersVersion_name, RegionalParametersVersion_value)
	golang_proto.RegisterEnum("org.packetbroker.v3.RegionalParametersVersion", RegionalParametersVersion_name, RegionalParametersVersion_value)
	proto.RegisterType((*RegionalParametersVersionValue)(nil), "org.packetbroker.v3.RegionalParametersVersionValue")
	golang_proto.RegisterType((*RegionalParametersVersionValue)(nil), "org.packetbroker.v3.RegionalParametersVersionValue")
}

func init() { proto.RegisterFile("packetbroker/api/v3/enums.proto", fileDescriptor_09f966b65c116bd0) }
func init() {
	golang_proto.RegisterFile("packetbroker/api/v3/enums.proto", fileDescriptor_09f966b65c116bd0)
}

var fileDescriptor_09f966b65c116bd0 = []byte{
	// 1146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x3d, 0x70, 0x13, 0xc7,
	0x17, 0xbf, 0x95, 0x64, 0x59, 0x5e, 0x7f, 0xfc, 0x1f, 0x87, 0xf9, 0x03, 0x81, 0x2c, 0x19, 0x9a,
	0x64, 0x54, 0x18, 0x7d, 0x18, 0x24, 0x4f, 0x26, 0xc5, 0xea, 0x6e, 0x2d, 0x5f, 0x74, 0xba, 0x3d,
	0xf6, 0x4e, 0x16, 0x4e, 0xb3, 0x73, 0x38, 0x17, 0x45, 0x83, 0xd0, 0x79, 0x4e, 0xc2, 0x19, 0x3a,
	0x4a, 0xca, 0x94, 0x99, 0xcc, 0x64, 0x26, 0x25, 0x25, 0x25, 0x25, 0x25, 0x25, 0x25, 0x25, 0x92,
	0x26, 0x33, 0x4c, 0xd2, 0x50, 0x52, 0x65, 0x32, 0xab, 0x93, 0x85, 0x2d, 0x4c, 0x77, 0xbf, 0xdf,
	0xfb, 0xb8, 0xf7, 0x7e, 0xfb, 0xde, 0x2e, 0xbe, 0x71, 0x14, 0x1c, 0x3e, 0x08, 0x87, 0xf7, 0xe3,
	0xe8, 0x41, 0x18, 0xdf, 0x0a, 0x8e, 0xba, 0xb7, 0x8e, 0xcb, 0xb7, 0xc2, 0xfe, 0xa3, 0x87, 0x83,
	0xad, 0xa3, 0x38, 0x1a, 0x46, 0xfa, 0xc5, 0x28, 0xee, 0x6c, 0x9d, 0x76, 0xda, 0x3a, 0x2e, 0xdf,
	0xfc, 0x09, 0x13, 0x11, 0x76, 0xba, 0x51, 0x3f, 0xe8, 0xb9, 0x41, 0x1c, 0x3c, 0x0c, 0x87, 0x61,
	0x3c, 0xd8, 0x0f, 0xe3, 0x41, 0x37, 0xea, 0xef, 0x07, 0xbd, 0x47, 0xa1, 0x6e, 0xe2, 0xa5, 0x63,
	0xf5, 0x71, 0x05, 0x7d, 0x85, 0xbe, 0xd9, 0x28, 0x6d, 0x6d, 0x9d, 0x93, 0x66, 0xeb, 0xb3, 0x39,
	0x44, 0x12, 0x9c, 0xff, 0x1b, 0xe1, 0x6c, 0xe2, 0xa4, 0xeb, 0x78, 0xa3, 0xe5, 0x34, 0x1c, 0xde,
	0x76, 0xa4, 0x60, 0x75, 0x8b, 0x3b, 0xa0, 0xe9, 0x1b, 0x18, 0xb3, 0x96, 0xac, 0xde, 0x29, 0xcb,
	0x6a, 0xa5, 0x00, 0x48, 0xe1, 0x96, 0x27, 0x77, 0x0a, 0x25, 0xb9, 0x53, 0xaa, 0x42, 0x4a, 0x61,
	0xc3, 0x91, 0x95, 0xca, 0x8e, 0xac, 0x54, 0x2b, 0x90, 0xd6, 0x31, 0xce, 0xb2, 0x96, 0xdc, 0x2e,
	0x97, 0x21, 0xa3, 0x6c, 0xb4, 0x25, 0x77, 0x8a, 0xb7, 0xa7, 0xbe, 0x4b, 0x33, 0xdf, 0xed, 0x4a,
	0x41, 0xde, 0x2e, 0x16, 0x20, 0xab, 0x7c, 0xa9, 0x27, 0x77, 0x4a, 0x65, 0x58, 0xd6, 0xd7, 0x70,
	0x2e, 0xf9, 0x96, 0x45, 0x58, 0x3d, 0x85, 0x4a, 0xb0, 0x76, 0x0a, 0x95, 0x61, 0x5d, 0x65, 0x69,
	0x08, 0xb9, 0x53, 0x2a, 0x4c, 0x23, 0x73, 0x0a, 0x5b, 0x8e, 0xac, 0xde, 0xb9, 0x2d, 0xab, 0x77,
	0x2a, 0xb0, 0xa2, 0xb0, 0x50, 0x15, 0x6f, 0x4f, 0x2b, 0xc6, 0xea, 0x2f, 0xed, 0xb6, 0x2c, 0xd5,
	0xb7, 0x61, 0x23, 0xff, 0x1d, 0xde, 0x34, 0xa3, 0x5f, 0xfa, 0xbd, 0x6e, 0xff, 0x41, 0x33, 0x1c,
	0x0c, 0x82, 0x4e, 0x68, 0xf4, 0x82, 0xc1, 0x40, 0x5f, 0xc5, 0xcb, 0x86, 0x4d, 0x3d, 0x4f, 0x52,
	0xd0, 0x3e, 0x82, 0x1a, 0xa0, 0x8f, 0xc0, 0x80, 0x54, 0xfe, 0x2e, 0xbe, 0xbc, 0x10, 0xee, 0xc6,
	0xdd, 0x28, 0xee, 0x0e, 0x1f, 0xab, 0xbf, 0xd8, 0xbc, 0xcd, 0x3c, 0x1f, 0x34, 0x7d, 0x19, 0xa7,
	0x6d, 0xde, 0x06, 0xa4, 0x48, 0x87, 0x8b, 0x26, 0xb5, 0x21, 0xa5, 0xe7, 0x70, 0x66, 0xcf, 0xaa,
	0xef, 0x41, 0x5a, 0xa5, 0x54, 0x5f, 0xca, 0x37, 0x93, 0xbf, 0x8b, 0x37, 0x67, 0xa9, 0xcc, 0xb0,
	0xd7, 0x3d, 0x0e, 0xe3, 0xc7, 0xde, 0x30, 0x18, 0x86, 0xd3, 0x9e, 0x0d, 0x83, 0xb9, 0x3e, 0x33,
	0x41, 0xd3, 0xd7, 0xf1, 0xca, 0x2e, 0x17, 0x6d, 0x2a, 0x4c, 0x66, 0x02, 0x52, 0xd0, 0x64, 0xb6,
	0xb5, 0xcf, 0x04, 0x33, 0x21, 0xa5, 0xa0, 0x2b, 0xb8, 0xc1, 0x3c, 0x8f, 0x99, 0x90, 0xce, 0xff,
	0x8e, 0xf0, 0xf5, 0xd6, 0xd1, 0x99, 0x22, 0xa3, 0xc3, 0x70, 0x30, 0xe8, 0xf6, 0x3b, 0x2c, 0x8e,
	0xa3, 0x58, 0xbf, 0x82, 0x37, 0x5b, 0xae, 0x6d, 0x39, 0x0d, 0x79, 0x72, 0xdc, 0x4c, 0x08, 0x2e,
	0x40, 0xd3, 0xaf, 0xe2, 0x4b, 0x33, 0x8b, 0xe0, 0x2d, 0xdf, 0x72, 0xea, 0xd2, 0xe5, 0xb6, 0x65,
	0x1c, 0x00, 0xd2, 0x2f, 0xe0, 0xf5, 0x26, 0xf5, 0x8d, 0x3d, 0xe9, 0x31, 0xcf, 0x53, 0xb3, 0x91,
	0xd2, 0x2f, 0xe2, 0xff, 0xcd, 0xbc, 0x2d, 0xc7, 0x67, 0xc2, 0xa1, 0x36, 0xa4, 0xf5, 0x2f, 0xf1,
	0x55, 0x87, 0xcb, 0x3d, 0xde, 0x64, 0xd2, 0x61, 0x7e, 0x9b, 0x8b, 0x86, 0x64, 0x8e, 0xe9, 0x72,
	0xcb, 0xf1, 0x3d, 0xc8, 0xe4, 0xff, 0x41, 0x98, 0x7c, 0xa2, 0xe1, 0xd9, 0xf2, 0xbe, 0xc0, 0xff,
	0x37, 0x79, 0xdb, 0x39, 0xb7, 0xc0, 0x35, 0x9c, 0xf3, 0x39, 0x97, 0x36, 0xf5, 0x59, 0xa2, 0x83,
	0x42, 0x8c, 0x0a, 0xfb, 0x00, 0x52, 0xfa, 0x26, 0x06, 0x83, 0xdb, 0xb6, 0xa5, 0xca, 0x93, 0x2e,
	0x35, 0x1a, 0xcc, 0x87, 0xf4, 0x59, 0xb6, 0xc6, 0xa8, 0xc1, 0x1d, 0xc8, 0xe8, 0x80, 0xd7, 0xfc,
	0x7b, 0x72, 0x57, 0xb0, 0xbb, 0x2d, 0xe6, 0x18, 0x07, 0xb0, 0x34, 0x4d, 0x7d, 0x4f, 0xba, 0xbc,
	0xcd, 0x04, 0x64, 0x95, 0xbd, 0xee, 0x7a, 0xb2, 0xe5, 0xd8, 0xdc, 0x68, 0x30, 0x13, 0x96, 0xf5,
	0x6b, 0xf8, 0xf2, 0xbc, 0xac, 0x05, 0x75, 0x72, 0xfa, 0x25, 0x7c, 0x61, 0x6e, 0x9c, 0x8b, 0xb1,
	0x92, 0x6f, 0xe2, 0x6b, 0x7e, 0x18, 0xc7, 0xe1, 0x60, 0x18, 0x77, 0x83, 0x1e, 0xed, 0x0f, 0xc3,
	0x7e, 0x3f, 0x70, 0x7b, 0xc1, 0x61, 0xf8, 0x30, 0xec, 0x0f, 0x55, 0xd4, 0x49, 0x83, 0xae, 0x4d,
	0x0d, 0xd6, 0x64, 0x8e, 0x9a, 0x1f, 0x8c, 0xb3, 0x96, 0x63, 0x72, 0x2e, 0x92, 0xf9, 0xe3, 0x2d,
	0x7f, 0x0a, 0x52, 0xf9, 0x1b, 0x18, 0x37, 0xa3, 0x1f, 0x1f, 0xf5, 0x82, 0xa1, 0x5a, 0xd7, 0x1c,
	0xce, 0xd8, 0x5c, 0xd0, 0x64, 0xe0, 0x76, 0xbd, 0x06, 0xa0, 0xfc, 0xbf, 0x08, 0x2f, 0x89, 0x6e,
	0xe7, 0xe7, 0xa1, 0xaa, 0x5f, 0x30, 0x6a, 0x9e, 0x9c, 0x01, 0x68, 0xea, 0xd4, 0x4f, 0x33, 0xd2,
	0xe0, 0x8e, 0x4f, 0x0d, 0x1f, 0x90, 0x52, 0x68, 0x6a, 0x51, 0x5d, 0x31, 0xe9, 0xd3, 0x9a, 0xcd,
	0x60, 0x69, 0xce, 0xfa, 0x54, 0xd4, 0x99, 0x2f, 0x69, 0xcb, 0xdf, 0x83, 0xac, 0x7e, 0x19, 0x5f,
	0x9c, 0xfb, 0x9e, 0x52, 0x20, 0xa3, 0xd2, 0xb7, 0x85, 0xe5, 0xb3, 0x45, 0xcb, 0x54, 0xb8, 0x69,
	0x48, 0x9d, 0xfa, 0xac, 0x4d, 0x0f, 0xe4, 0xbe, 0xe5, 0x59, 0x35, 0xcb, 0xb6, 0x7c, 0x25, 0xdc,
	0x75, 0x7c, 0x25, 0x09, 0x3b, 0xc7, 0xba, 0x32, 0xef, 0xc2, 0x17, 0x74, 0x77, 0xd7, 0x32, 0x00,
	0xab, 0x31, 0x4c, 0xfc, 0x4f, 0xa8, 0xd5, 0x9b, 0x99, 0x5c, 0x0a, 0x52, 0x37, 0x33, 0xb9, 0x34,
	0xa4, 0xf3, 0x55, 0xbc, 0x4a, 0x5d, 0xab, 0x11, 0xce, 0xb6, 0x68, 0x1d, 0xaf, 0x4c, 0x4f, 0xd8,
	0x4b, 0xd6, 0x48, 0x2d, 0x95, 0xeb, 0x0a, 0xbe, 0x3f, 0xdd, 0xa2, 0x35, 0x9c, 0x13, 0xec, 0x7b,
	0x66, 0x28, 0x5b, 0x2a, 0x5f, 0xc2, 0x1b, 0x7e, 0x10, 0x77, 0xc2, 0xa1, 0xab, 0xee, 0xe4, 0xc3,
	0xa8, 0xa7, 0x2e, 0x12, 0xdf, 0x2b, 0x14, 0x4a, 0x72, 0xbf, 0x28, 0x0b, 0xa0, 0x4d, 0x47, 0xe6,
	0x04, 0x2b, 0x06, 0xe5, 0xff, 0x42, 0xf8, 0xea, 0x67, 0x2f, 0xd8, 0x93, 0xf8, 0xe2, 0x42, 0x7c,
	0x82, 0x65, 0x11, 0x90, 0xba, 0x70, 0x85, 0x3b, 0x67, 0x4a, 0x92, 0x42, 0xea, 0x13, 0xae, 0x06,
	0xe9, 0x05, 0xae, 0x2c, 0x69, 0x32, 0xc0, 0x73, 0xae, 0x28, 0x29, 0x2c, 0x2d, 0x30, 0xb5, 0x64,
	0x88, 0x15, 0x93, 0x74, 0x20, 0x0b, 0xb0, 0xbc, 0xc0, 0x14, 0x21, 0xb7, 0xc0, 0x94, 0x66, 0xa2,
	0x7f, 0x64, 0xca, 0x80, 0x6b, 0x7f, 0xa0, 0x57, 0x23, 0x82, 0x5e, 0x8f, 0x08, 0x7a, 0x33, 0x22,
	0xda, 0xdb, 0x11, 0xd1, 0xde, 0x8d, 0x88, 0xf6, 0x7e, 0x44, 0xb4, 0x0f, 0x23, 0x82, 0x9e, 0x8c,
	0x09, 0x7a, 0x3a, 0x26, 0xda, 0xb3, 0x31, 0x41, 0xcf, 0xc7, 0x44, 0x7b, 0x31, 0x26, 0xda, 0xcb,
	0x31, 0xd1, 0x5e, 0x8d, 0x09, 0x7a, 0x3d, 0x26, 0xe8, 0xcd, 0x98, 0x68, 0x6f, 0xc7, 0x04, 0xbd,
	0x1b, 0x13, 0xed, 0xfd, 0x98, 0xa0, 0x0f, 0x63, 0xa2, 0x3d, 0x99, 0x10, 0xed, 0xe9, 0x84, 0xa0,
	0x5f, 0x27, 0x44, 0xfb, 0x6d, 0x42, 0xd0, 0x9f, 0x13, 0xa2, 0x3d, 0x9b, 0x10, 0xed, 0xf9, 0x84,
	0xa0, 0x17, 0x13, 0x82, 0x5e, 0x4e, 0x08, 0xfa, 0xe1, 0xeb, 0x4e, 0x74, 0xf6, 0x3d, 0x8b, 0xe2,
	0xce, 0xec, 0xfd, 0xfc, 0xf6, 0x34, 0x7f, 0x3f, 0x3b, 0x7d, 0x47, 0xcb, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x73, 0x73, 0x44, 0xc9, 0x6a, 0x07, 0x00, 0x00,
}

func (x Region) String() string {
	s, ok := Region_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x DownlinkMessageClass) String() string {
	s, ok := DownlinkMessageClass_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x DownlinkMessagePriority) String() string {
	s, ok := DownlinkMessagePriority_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x MessageDeliveryState) String() string {
	s, ok := MessageDeliveryState_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x UplinkMessageProcessingError) String() string {
	s, ok := UplinkMessageProcessingError_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x DownlinkMessageProcessingError) String() string {
	s, ok := DownlinkMessageProcessingError_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x TerrestrialAntennaPlacement) String() string {
	s, ok := TerrestrialAntennaPlacement_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x Modulation) String() string {
	s, ok := Modulation_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x Right) String() string {
	s, ok := Right_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x APIKeyState) String() string {
	s, ok := APIKeyState_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x TargetProtocol) String() string {
	s, ok := TargetProtocol_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x RegionalParametersVersion) String() string {
	s, ok := RegionalParametersVersion_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *RegionalParametersVersionValue) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RegionalParametersVersionValue)
	if !ok {
		that2, ok := that.(RegionalParametersVersionValue)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}
func (m *RegionalParametersVersionValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegionalParametersVersionValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegionalParametersVersionValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != 0 {
		i = encodeVarintEnums(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEnums(dAtA []byte, offset int, v uint64) int {
	offset -= sovEnums(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedRegionalParametersVersionValue(r randyEnums, easy bool) *RegionalParametersVersionValue {
	this := &RegionalParametersVersionValue{}
	this.Value = RegionalParametersVersion([]int32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}[r.Intn(11)])
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyEnums interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneEnums(r randyEnums) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringEnums(r randyEnums) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneEnums(r)
	}
	return string(tmps)
}
func randUnrecognizedEnums(r randyEnums, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldEnums(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldEnums(dAtA []byte, r randyEnums, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateEnums(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateEnums(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateEnums(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateEnums(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateEnums(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateEnums(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateEnums(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *RegionalParametersVersionValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value != 0 {
		n += 1 + sovEnums(uint64(m.Value))
	}
	return n
}

func sovEnums(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEnums(x uint64) (n int) {
	return sovEnums(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *RegionalParametersVersionValue) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RegionalParametersVersionValue{`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringEnums(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *RegionalParametersVersionValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEnums
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegionalParametersVersionValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegionalParametersVersionValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEnums
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= RegionalParametersVersion(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEnums(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEnums
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEnums
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEnums(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEnums
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEnums
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEnums
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEnums
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEnums
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEnums
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEnums        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEnums          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEnums = fmt.Errorf("proto: unexpected end of group")
)
