// Copyright © 2020 The Things Industries B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: packetbroker/api/v3/joinserver.proto

package packetbroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier of the Join Server.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the Join Server.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// JoinEUI prefixes of this Join Server.
	JoinEuiPrefixes []*JoinEUIPrefix `protobuf:"bytes,3,rep,name=join_eui_prefixes,json=joinEuiPrefixes,proto3" json:"join_eui_prefixes,omitempty"`
	// Administrative contact.
	AdministrativeContact *ContactInfo `protobuf:"bytes,4,opt,name=administrative_contact,json=administrativeContact,proto3" json:"administrative_contact,omitempty"`
	// Technical contact.
	TechnicalContact *ContactInfo `protobuf:"bytes,5,opt,name=technical_contact,json=technicalContact,proto3" json:"technical_contact,omitempty"`
	// Indicates whether the Join Server is publicly listed.
	Listed bool `protobuf:"varint,6,opt,name=listed,proto3" json:"listed,omitempty"`
	// Types that are assignable to Resolver:
	//	*JoinServer_Lookup
	//	*JoinServer_Fixed
	Resolver isJoinServer_Resolver `protobuf_oneof:"resolver"`
}

func (x *JoinServer) Reset() {
	*x = JoinServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packetbroker_api_v3_joinserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinServer) ProtoMessage() {}

func (x *JoinServer) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_joinserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinServer.ProtoReflect.Descriptor instead.
func (*JoinServer) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_joinserver_proto_rawDescGZIP(), []int{0}
}

func (x *JoinServer) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JoinServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinServer) GetJoinEuiPrefixes() []*JoinEUIPrefix {
	if x != nil {
		return x.JoinEuiPrefixes
	}
	return nil
}

func (x *JoinServer) GetAdministrativeContact() *ContactInfo {
	if x != nil {
		return x.AdministrativeContact
	}
	return nil
}

func (x *JoinServer) GetTechnicalContact() *ContactInfo {
	if x != nil {
		return x.TechnicalContact
	}
	return nil
}

func (x *JoinServer) GetListed() bool {
	if x != nil {
		return x.Listed
	}
	return false
}

func (m *JoinServer) GetResolver() isJoinServer_Resolver {
	if m != nil {
		return m.Resolver
	}
	return nil
}

func (x *JoinServer) GetLookup() *Target {
	if x, ok := x.GetResolver().(*JoinServer_Lookup); ok {
		return x.Lookup
	}
	return nil
}

func (x *JoinServer) GetFixed() *JoinServerFixedEndpoint {
	if x, ok := x.GetResolver().(*JoinServer_Fixed); ok {
		return x.Fixed
	}
	return nil
}

type isJoinServer_Resolver interface {
	isJoinServer_Resolver()
}

type JoinServer_Lookup struct {
	// Target to lookup the endpoint based on DevEUI for this set of JoinEUIs.
	Lookup *Target `protobuf:"bytes,7,opt,name=lookup,proto3,oneof"`
}

type JoinServer_Fixed struct {
	// Fixed endpoint which handles activations from any DevEUI for this set of JoinEUIs.
	Fixed *JoinServerFixedEndpoint `protobuf:"bytes,8,opt,name=fixed,proto3,oneof"`
}

func (*JoinServer_Lookup) isJoinServer_Resolver() {}

func (*JoinServer_Fixed) isJoinServer_Resolver() {}

type JoinEUIPrefix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// Significant bits of value.
	Length uint32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *JoinEUIPrefix) Reset() {
	*x = JoinEUIPrefix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packetbroker_api_v3_joinserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinEUIPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEUIPrefix) ProtoMessage() {}

func (x *JoinEUIPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_joinserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEUIPrefix.ProtoReflect.Descriptor instead.
func (*JoinEUIPrefix) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_joinserver_proto_rawDescGZIP(), []int{1}
}

func (x *JoinEUIPrefix) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *JoinEUIPrefix) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type JoinServerFixedEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// LoRa Alliance NetID of the Member.
	NetId uint32 `protobuf:"varint,1,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	// ID assigned by the Member (optional).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Cluster of the Member (optional).
	ClusterId string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
}

func (x *JoinServerFixedEndpoint) Reset() {
	*x = JoinServerFixedEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packetbroker_api_v3_joinserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinServerFixedEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinServerFixedEndpoint) ProtoMessage() {}

func (x *JoinServerFixedEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_joinserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinServerFixedEndpoint.ProtoReflect.Descriptor instead.
func (*JoinServerFixedEndpoint) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_joinserver_proto_rawDescGZIP(), []int{2}
}

func (x *JoinServerFixedEndpoint) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *JoinServerFixedEndpoint) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *JoinServerFixedEndpoint) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

var File_packetbroker_api_v3_joinserver_proto protoreflect.FileDescriptor

var file_packetbroker_api_v3_joinserver_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x33, 0x2f, 0x6a, 0x6f, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x33, 0x1a, 0x21, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x33,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x33, 0x2f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc9, 0x03, 0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x4e, 0x0a, 0x11, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x65, 0x75, 0x69, 0x5f,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x2e, 0x76, 0x33, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x45, 0x55, 0x49, 0x50, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x52, 0x0f, 0x6a, 0x6f, 0x69, 0x6e, 0x45, 0x75, 0x69, 0x50, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x65, 0x73, 0x12, 0x57, 0x0a, 0x16, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x15, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x4d, 0x0a, 0x11,
	0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x10, 0x74, 0x65, 0x63, 0x68, 0x6e,
	0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x69, 0x73, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x69, 0x73,
	0x74, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x44, 0x0a, 0x05, 0x66, 0x69,
	0x78, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x33, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x69, 0x78, 0x65, 0x64, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x66, 0x69, 0x78, 0x65, 0x64,
	0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x22, 0x3d, 0x0a, 0x0d,
	0x4a, 0x6f, 0x69, 0x6e, 0x45, 0x55, 0x49, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x6c, 0x0a, 0x17, 0x4a,
	0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x69, 0x78, 0x65, 0x64, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x6f, 0x2e,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x33, 0x3b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packetbroker_api_v3_joinserver_proto_rawDescOnce sync.Once
	file_packetbroker_api_v3_joinserver_proto_rawDescData = file_packetbroker_api_v3_joinserver_proto_rawDesc
)

func file_packetbroker_api_v3_joinserver_proto_rawDescGZIP() []byte {
	file_packetbroker_api_v3_joinserver_proto_rawDescOnce.Do(func() {
		file_packetbroker_api_v3_joinserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_packetbroker_api_v3_joinserver_proto_rawDescData)
	})
	return file_packetbroker_api_v3_joinserver_proto_rawDescData
}

var file_packetbroker_api_v3_joinserver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_packetbroker_api_v3_joinserver_proto_goTypes = []interface{}{
	(*JoinServer)(nil),              // 0: org.packetbroker.v3.JoinServer
	(*JoinEUIPrefix)(nil),           // 1: org.packetbroker.v3.JoinEUIPrefix
	(*JoinServerFixedEndpoint)(nil), // 2: org.packetbroker.v3.JoinServerFixedEndpoint
	(*ContactInfo)(nil),             // 3: org.packetbroker.v3.ContactInfo
	(*Target)(nil),                  // 4: org.packetbroker.v3.Target
}
var file_packetbroker_api_v3_joinserver_proto_depIdxs = []int32{
	1, // 0: org.packetbroker.v3.JoinServer.join_eui_prefixes:type_name -> org.packetbroker.v3.JoinEUIPrefix
	3, // 1: org.packetbroker.v3.JoinServer.administrative_contact:type_name -> org.packetbroker.v3.ContactInfo
	3, // 2: org.packetbroker.v3.JoinServer.technical_contact:type_name -> org.packetbroker.v3.ContactInfo
	4, // 3: org.packetbroker.v3.JoinServer.lookup:type_name -> org.packetbroker.v3.Target
	2, // 4: org.packetbroker.v3.JoinServer.fixed:type_name -> org.packetbroker.v3.JoinServerFixedEndpoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_packetbroker_api_v3_joinserver_proto_init() }
func file_packetbroker_api_v3_joinserver_proto_init() {
	if File_packetbroker_api_v3_joinserver_proto != nil {
		return
	}
	file_packetbroker_api_v3_contact_proto_init()
	file_packetbroker_api_v3_target_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_packetbroker_api_v3_joinserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packetbroker_api_v3_joinserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinEUIPrefix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packetbroker_api_v3_joinserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinServerFixedEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_packetbroker_api_v3_joinserver_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*JoinServer_Lookup)(nil),
		(*JoinServer_Fixed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packetbroker_api_v3_joinserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packetbroker_api_v3_joinserver_proto_goTypes,
		DependencyIndexes: file_packetbroker_api_v3_joinserver_proto_depIdxs,
		MessageInfos:      file_packetbroker_api_v3_joinserver_proto_msgTypes,
	}.Build()
	File_packetbroker_api_v3_joinserver_proto = out.File
	file_packetbroker_api_v3_joinserver_proto_rawDesc = nil
	file_packetbroker_api_v3_joinserver_proto_goTypes = nil
	file_packetbroker_api_v3_joinserver_proto_depIdxs = nil
}
