// Copyright © 2020 The Things Industries B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: packetbroker/api/v3/network.proto

package packetbroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Network struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authority of the network.
	// If empty, Packet Broker is the authority.
	Authority string `protobuf:"bytes,10,opt,name=authority,proto3" json:"authority,omitempty"`
	// LoRa Alliance NetID of the Member.
	NetId uint32 `protobuf:"varint,1,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	// Name of the network.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// DevAddr prefixes of the tenant.
	DevAddrBlocks []*DevAddrBlock `protobuf:"bytes,3,rep,name=dev_addr_blocks,json=devAddrBlocks,proto3" json:"dev_addr_blocks,omitempty"`
	// Administrative contact.
	AdministrativeContact *ContactInfo `protobuf:"bytes,4,opt,name=administrative_contact,json=administrativeContact,proto3" json:"administrative_contact,omitempty"`
	// Technical contact.
	TechnicalContact *ContactInfo `protobuf:"bytes,5,opt,name=technical_contact,json=technicalContact,proto3" json:"technical_contact,omitempty"`
	// Indicates whether the network is publicly listed in the catalog.
	Listed bool `protobuf:"varint,6,opt,name=listed,proto3" json:"listed,omitempty"`
	// Optional target information.
	Target *Target `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	// Delegated network.
	DelegatedNetId *wrapperspb.UInt32Value `protobuf:"bytes,8,opt,name=delegated_net_id,json=delegatedNetId,proto3" json:"delegated_net_id,omitempty"`
	// Networks that this network represents.
	RepresentsNetIds []uint32 `protobuf:"varint,9,rep,packed,name=represents_net_ids,json=representsNetIds,proto3" json:"represents_net_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_network_proto_rawDescGZIP(), []int{0}
}

func (x *Network) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *Network) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetDevAddrBlocks() []*DevAddrBlock {
	if x != nil {
		return x.DevAddrBlocks
	}
	return nil
}

func (x *Network) GetAdministrativeContact() *ContactInfo {
	if x != nil {
		return x.AdministrativeContact
	}
	return nil
}

func (x *Network) GetTechnicalContact() *ContactInfo {
	if x != nil {
		return x.TechnicalContact
	}
	return nil
}

func (x *Network) GetListed() bool {
	if x != nil {
		return x.Listed
	}
	return false
}

func (x *Network) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Network) GetDelegatedNetId() *wrapperspb.UInt32Value {
	if x != nil {
		return x.DelegatedNetId
	}
	return nil
}

func (x *Network) GetRepresentsNetIds() []uint32 {
	if x != nil {
		return x.RepresentsNetIds
	}
	return nil
}

type Tenant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authority of the tenant.
	// If empty, Packet Broker is the authority.
	Authority string `protobuf:"bytes,10,opt,name=authority,proto3" json:"authority,omitempty"`
	// LoRa Alliance NetID of the Member.
	NetId uint32 `protobuf:"varint,1,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	// ID assigned by the Member.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Name of the tenant.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// DevAddr prefixes of the tenant.
	DevAddrBlocks []*DevAddrBlock `protobuf:"bytes,5,rep,name=dev_addr_blocks,json=devAddrBlocks,proto3" json:"dev_addr_blocks,omitempty"`
	// Administrative contact.
	AdministrativeContact *ContactInfo `protobuf:"bytes,6,opt,name=administrative_contact,json=administrativeContact,proto3" json:"administrative_contact,omitempty"`
	// Technical contact.
	TechnicalContact *ContactInfo `protobuf:"bytes,7,opt,name=technical_contact,json=technicalContact,proto3" json:"technical_contact,omitempty"`
	// Indicates whether the tenant is listed in the catalog.
	Listed bool `protobuf:"varint,8,opt,name=listed,proto3" json:"listed,omitempty"`
	// Optional target information.
	Target        *Target `protobuf:"bytes,9,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_network_proto_rawDescGZIP(), []int{1}
}

func (x *Tenant) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *Tenant) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *Tenant) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetDevAddrBlocks() []*DevAddrBlock {
	if x != nil {
		return x.DevAddrBlocks
	}
	return nil
}

func (x *Tenant) GetAdministrativeContact() *ContactInfo {
	if x != nil {
		return x.AdministrativeContact
	}
	return nil
}

func (x *Tenant) GetTechnicalContact() *ContactInfo {
	if x != nil {
		return x.TechnicalContact
	}
	return nil
}

func (x *Tenant) GetListed() bool {
	if x != nil {
		return x.Listed
	}
	return false
}

func (x *Tenant) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

type NetworkOrTenant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*NetworkOrTenant_Network
	//	*NetworkOrTenant_Tenant
	Value         isNetworkOrTenant_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkOrTenant) Reset() {
	*x = NetworkOrTenant{}
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkOrTenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkOrTenant) ProtoMessage() {}

func (x *NetworkOrTenant) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkOrTenant.ProtoReflect.Descriptor instead.
func (*NetworkOrTenant) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_network_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkOrTenant) GetValue() isNetworkOrTenant_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NetworkOrTenant) GetNetwork() *Network {
	if x != nil {
		if x, ok := x.Value.(*NetworkOrTenant_Network); ok {
			return x.Network
		}
	}
	return nil
}

func (x *NetworkOrTenant) GetTenant() *Tenant {
	if x != nil {
		if x, ok := x.Value.(*NetworkOrTenant_Tenant); ok {
			return x.Tenant
		}
	}
	return nil
}

type isNetworkOrTenant_Value interface {
	isNetworkOrTenant_Value()
}

type NetworkOrTenant_Network struct {
	Network *Network `protobuf:"bytes,1,opt,name=network,proto3,oneof"`
}

type NetworkOrTenant_Tenant struct {
	Tenant *Tenant `protobuf:"bytes,2,opt,name=tenant,proto3,oneof"`
}

func (*NetworkOrTenant_Network) isNetworkOrTenant_Value() {}

func (*NetworkOrTenant_Tenant) isNetworkOrTenant_Value() {}

type DevAddrPrefix struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value uint32                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// Significant bits of value.
	Length        uint32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevAddrPrefix) Reset() {
	*x = DevAddrPrefix{}
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevAddrPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevAddrPrefix) ProtoMessage() {}

func (x *DevAddrPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevAddrPrefix.ProtoReflect.Descriptor instead.
func (*DevAddrPrefix) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_network_proto_rawDescGZIP(), []int{3}
}

func (x *DevAddrPrefix) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DevAddrPrefix) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type DevAddrBlock struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Prefix *DevAddrPrefix         `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Cluster of the Home Network Member (optional).
	HomeNetworkClusterId string `protobuf:"bytes,2,opt,name=home_network_cluster_id,json=homeNetworkClusterId,proto3" json:"home_network_cluster_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DevAddrBlock) Reset() {
	*x = DevAddrBlock{}
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevAddrBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevAddrBlock) ProtoMessage() {}

func (x *DevAddrBlock) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevAddrBlock.ProtoReflect.Descriptor instead.
func (*DevAddrBlock) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_network_proto_rawDescGZIP(), []int{4}
}

func (x *DevAddrBlock) GetPrefix() *DevAddrPrefix {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *DevAddrBlock) GetHomeNetworkClusterId() string {
	if x != nil {
		return x.HomeNetworkClusterId
	}
	return ""
}

type NetworkAPIKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the API key.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// LoRa Alliance NetID of the Member.
	NetId uint32 `protobuf:"varint,2,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	// ID assigned by the Member.
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Cluster of the Member.
	ClusterId string `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Network rights.
	Rights []Right `protobuf:"varint,7,rep,packed,name=rights,proto3,enum=org.packetbroker.v3.Right" json:"rights,omitempty"`
	// Last authentication timestamp.
	AuthenticatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=authenticated_at,json=authenticatedAt,proto3" json:"authenticated_at,omitempty"`
	// Secret key value.
	Key string `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	// Key state.
	State         APIKeyState `protobuf:"varint,8,opt,name=state,proto3,enum=org.packetbroker.v3.APIKeyState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAPIKey) Reset() {
	*x = NetworkAPIKey{}
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAPIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAPIKey) ProtoMessage() {}

func (x *NetworkAPIKey) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAPIKey.ProtoReflect.Descriptor instead.
func (*NetworkAPIKey) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_network_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkAPIKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *NetworkAPIKey) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *NetworkAPIKey) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NetworkAPIKey) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NetworkAPIKey) GetRights() []Right {
	if x != nil {
		return x.Rights
	}
	return nil
}

func (x *NetworkAPIKey) GetAuthenticatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthenticatedAt
	}
	return nil
}

func (x *NetworkAPIKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NetworkAPIKey) GetState() APIKeyState {
	if x != nil {
		return x.State
	}
	return APIKeyState_REQUESTED
}

type NetworkTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LoRa Alliance NetID of the Member.
	NetId uint32 `protobuf:"varint,1,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	// Tenant ID assigned by the Member (optional).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Target information.
	Target        *Target `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkTarget) Reset() {
	*x = NetworkTarget{}
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTarget) ProtoMessage() {}

func (x *NetworkTarget) ProtoReflect() protoreflect.Message {
	mi := &file_packetbroker_api_v3_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTarget.ProtoReflect.Descriptor instead.
func (*NetworkTarget) Descriptor() ([]byte, []int) {
	return file_packetbroker_api_v3_network_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkTarget) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *NetworkTarget) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NetworkTarget) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

var File_packetbroker_api_v3_network_proto protoreflect.FileDescriptor

const file_packetbroker_api_v3_network_proto_rawDesc = "" +
	"\n" +
	"!packetbroker/api/v3/network.proto\x12\x13org.packetbroker.v3\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a!packetbroker/api/v3/contact.proto\x1a\x1fpacketbroker/api/v3/enums.proto\x1a packetbroker/api/v3/target.proto\"\x88\x04\n" +
	"\aNetwork\x12\x1c\n" +
	"\tauthority\x18\n" +
	" \x01(\tR\tauthority\x12\x15\n" +
	"\x06net_id\x18\x01 \x01(\rR\x05netId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12I\n" +
	"\x0fdev_addr_blocks\x18\x03 \x03(\v2!.org.packetbroker.v3.DevAddrBlockR\rdevAddrBlocks\x12W\n" +
	"\x16administrative_contact\x18\x04 \x01(\v2 .org.packetbroker.v3.ContactInfoR\x15administrativeContact\x12M\n" +
	"\x11technical_contact\x18\x05 \x01(\v2 .org.packetbroker.v3.ContactInfoR\x10technicalContact\x12\x16\n" +
	"\x06listed\x18\x06 \x01(\bR\x06listed\x123\n" +
	"\x06target\x18\a \x01(\v2\x1b.org.packetbroker.v3.TargetR\x06target\x12F\n" +
	"\x10delegated_net_id\x18\b \x01(\v2\x1c.google.protobuf.UInt32ValueR\x0edelegatedNetId\x12,\n" +
	"\x12represents_net_ids\x18\t \x03(\rR\x10representsNetIds\"\xb4\x03\n" +
	"\x06Tenant\x12\x1c\n" +
	"\tauthority\x18\n" +
	" \x01(\tR\tauthority\x12\x15\n" +
	"\x06net_id\x18\x01 \x01(\rR\x05netId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12I\n" +
	"\x0fdev_addr_blocks\x18\x05 \x03(\v2!.org.packetbroker.v3.DevAddrBlockR\rdevAddrBlocks\x12W\n" +
	"\x16administrative_contact\x18\x06 \x01(\v2 .org.packetbroker.v3.ContactInfoR\x15administrativeContact\x12M\n" +
	"\x11technical_contact\x18\a \x01(\v2 .org.packetbroker.v3.ContactInfoR\x10technicalContact\x12\x16\n" +
	"\x06listed\x18\b \x01(\bR\x06listed\x123\n" +
	"\x06target\x18\t \x01(\v2\x1b.org.packetbroker.v3.TargetR\x06targetJ\x04\b\x03\x10\x04\"\x8b\x01\n" +
	"\x0fNetworkOrTenant\x128\n" +
	"\anetwork\x18\x01 \x01(\v2\x1c.org.packetbroker.v3.NetworkH\x00R\anetwork\x125\n" +
	"\x06tenant\x18\x02 \x01(\v2\x1b.org.packetbroker.v3.TenantH\x00R\x06tenantB\a\n" +
	"\x05value\"=\n" +
	"\rDevAddrPrefix\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\x12\x16\n" +
	"\x06length\x18\x02 \x01(\rR\x06length\"\x81\x01\n" +
	"\fDevAddrBlock\x12:\n" +
	"\x06prefix\x18\x01 \x01(\v2\".org.packetbroker.v3.DevAddrPrefixR\x06prefix\x125\n" +
	"\x17home_network_cluster_id\x18\x02 \x01(\tR\x14homeNetworkClusterId\"\xbe\x02\n" +
	"\rNetworkAPIKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x15\n" +
	"\x06net_id\x18\x02 \x01(\rR\x05netId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\x122\n" +
	"\x06rights\x18\a \x03(\x0e2\x1a.org.packetbroker.v3.RightR\x06rights\x12E\n" +
	"\x10authenticated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fauthenticatedAt\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x126\n" +
	"\x05state\x18\b \x01(\x0e2 .org.packetbroker.v3.APIKeyStateR\x05state\"x\n" +
	"\rNetworkTarget\x12\x15\n" +
	"\x06net_id\x18\x01 \x01(\rR\x05netId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x123\n" +
	"\x06target\x18\x03 \x01(\v2\x1b.org.packetbroker.v3.TargetR\x06targetB)Z'go.packetbroker.org/api/v3;packetbrokerb\x06proto3"

var (
	file_packetbroker_api_v3_network_proto_rawDescOnce sync.Once
	file_packetbroker_api_v3_network_proto_rawDescData []byte
)

func file_packetbroker_api_v3_network_proto_rawDescGZIP() []byte {
	file_packetbroker_api_v3_network_proto_rawDescOnce.Do(func() {
		file_packetbroker_api_v3_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packetbroker_api_v3_network_proto_rawDesc), len(file_packetbroker_api_v3_network_proto_rawDesc)))
	})
	return file_packetbroker_api_v3_network_proto_rawDescData
}

var file_packetbroker_api_v3_network_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_packetbroker_api_v3_network_proto_goTypes = []any{
	(*Network)(nil),                // 0: org.packetbroker.v3.Network
	(*Tenant)(nil),                 // 1: org.packetbroker.v3.Tenant
	(*NetworkOrTenant)(nil),        // 2: org.packetbroker.v3.NetworkOrTenant
	(*DevAddrPrefix)(nil),          // 3: org.packetbroker.v3.DevAddrPrefix
	(*DevAddrBlock)(nil),           // 4: org.packetbroker.v3.DevAddrBlock
	(*NetworkAPIKey)(nil),          // 5: org.packetbroker.v3.NetworkAPIKey
	(*NetworkTarget)(nil),          // 6: org.packetbroker.v3.NetworkTarget
	(*ContactInfo)(nil),            // 7: org.packetbroker.v3.ContactInfo
	(*Target)(nil),                 // 8: org.packetbroker.v3.Target
	(*wrapperspb.UInt32Value)(nil), // 9: google.protobuf.UInt32Value
	(Right)(0),                     // 10: org.packetbroker.v3.Right
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(APIKeyState)(0),               // 12: org.packetbroker.v3.APIKeyState
}
var file_packetbroker_api_v3_network_proto_depIdxs = []int32{
	4,  // 0: org.packetbroker.v3.Network.dev_addr_blocks:type_name -> org.packetbroker.v3.DevAddrBlock
	7,  // 1: org.packetbroker.v3.Network.administrative_contact:type_name -> org.packetbroker.v3.ContactInfo
	7,  // 2: org.packetbroker.v3.Network.technical_contact:type_name -> org.packetbroker.v3.ContactInfo
	8,  // 3: org.packetbroker.v3.Network.target:type_name -> org.packetbroker.v3.Target
	9,  // 4: org.packetbroker.v3.Network.delegated_net_id:type_name -> google.protobuf.UInt32Value
	4,  // 5: org.packetbroker.v3.Tenant.dev_addr_blocks:type_name -> org.packetbroker.v3.DevAddrBlock
	7,  // 6: org.packetbroker.v3.Tenant.administrative_contact:type_name -> org.packetbroker.v3.ContactInfo
	7,  // 7: org.packetbroker.v3.Tenant.technical_contact:type_name -> org.packetbroker.v3.ContactInfo
	8,  // 8: org.packetbroker.v3.Tenant.target:type_name -> org.packetbroker.v3.Target
	0,  // 9: org.packetbroker.v3.NetworkOrTenant.network:type_name -> org.packetbroker.v3.Network
	1,  // 10: org.packetbroker.v3.NetworkOrTenant.tenant:type_name -> org.packetbroker.v3.Tenant
	3,  // 11: org.packetbroker.v3.DevAddrBlock.prefix:type_name -> org.packetbroker.v3.DevAddrPrefix
	10, // 12: org.packetbroker.v3.NetworkAPIKey.rights:type_name -> org.packetbroker.v3.Right
	11, // 13: org.packetbroker.v3.NetworkAPIKey.authenticated_at:type_name -> google.protobuf.Timestamp
	12, // 14: org.packetbroker.v3.NetworkAPIKey.state:type_name -> org.packetbroker.v3.APIKeyState
	8,  // 15: org.packetbroker.v3.NetworkTarget.target:type_name -> org.packetbroker.v3.Target
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_packetbroker_api_v3_network_proto_init() }
func file_packetbroker_api_v3_network_proto_init() {
	if File_packetbroker_api_v3_network_proto != nil {
		return
	}
	file_packetbroker_api_v3_contact_proto_init()
	file_packetbroker_api_v3_enums_proto_init()
	file_packetbroker_api_v3_target_proto_init()
	file_packetbroker_api_v3_network_proto_msgTypes[2].OneofWrappers = []any{
		(*NetworkOrTenant_Network)(nil),
		(*NetworkOrTenant_Tenant)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packetbroker_api_v3_network_proto_rawDesc), len(file_packetbroker_api_v3_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packetbroker_api_v3_network_proto_goTypes,
		DependencyIndexes: file_packetbroker_api_v3_network_proto_depIdxs,
		MessageInfos:      file_packetbroker_api_v3_network_proto_msgTypes,
	}.Build()
	File_packetbroker_api_v3_network_proto = out.File
	file_packetbroker_api_v3_network_proto_goTypes = nil
	file_packetbroker_api_v3_network_proto_depIdxs = nil
}
