// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: packetbroker/api/v3/target.proto

package packetbroker

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Target struct {
	// Protocol to use.
	Protocol Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=org.packetbroker.v3.Protocol" json:"protocol,omitempty"`
	// Address of the target.
	// When using an HTTP protocol, this can be a URL with scheme, host, port and path.
	// This value may be empty if the protocol supports service lookup (e.g. via DNS).
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Path of the Forwarding Network Server (fNS) endpoint.
	FNsPath string `protobuf:"bytes,9,opt,name=f_ns_path,json=fNsPath,proto3" json:"f_ns_path,omitempty"`
	// Path of the Serving Network Server (sNS) endpoint.
	SNsPath string `protobuf:"bytes,10,opt,name=s_ns_path,json=sNsPath,proto3" json:"s_ns_path,omitempty"`
	// Path of the Home Network Server (hNS) endpoint.
	HNsPath string `protobuf:"bytes,11,opt,name=h_ns_path,json=hNsPath,proto3" json:"h_ns_path,omitempty"`
	// PEM encoded root CAs to verify the server certificate.
	// This value may be empty to use the default trusted root certificates.
	RootCas []byte `protobuf:"bytes,6,opt,name=root_cas,json=rootCas,proto3" json:"root_cas,omitempty"`
	// Default authentication when no custom authentication per NetID is set.
	//
	// Types that are valid to be assigned to DefaultAuthentication:
	//	*Target_BasicAuth_
	//	*Target_CustomAuth_
	//	*Target_TlsClientAuth
	//	*Target_PbTokenAuth
	DefaultAuthentication isTarget_DefaultAuthentication `protobuf_oneof:"default_authentication"`
	// Custom authentication per originating NetID.
	OriginNetIdAuthentication map[uint32]*Target_Authentication `protobuf:"bytes,8,rep,name=origin_net_id_authentication,json=originNetIdAuthentication,proto3" json:"origin_net_id_authentication,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral      struct{}                          `json:"-"`
	XXX_unrecognized          []byte                            `json:"-"`
	XXX_sizecache             int32                             `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_92034e0542da6cfe, []int{0}
}
func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

type isTarget_DefaultAuthentication interface {
	isTarget_DefaultAuthentication()
}

type Target_BasicAuth_ struct {
	BasicAuth *Target_BasicAuth `protobuf:"bytes,3,opt,name=basic_auth,json=basicAuth,proto3,oneof" json:"basic_auth,omitempty"`
}
type Target_CustomAuth_ struct {
	CustomAuth *Target_CustomAuth `protobuf:"bytes,4,opt,name=custom_auth,json=customAuth,proto3,oneof" json:"custom_auth,omitempty"`
}
type Target_TlsClientAuth struct {
	TlsClientAuth *Target_TLSClientAuth `protobuf:"bytes,5,opt,name=tls_client_auth,json=tlsClientAuth,proto3,oneof" json:"tls_client_auth,omitempty"`
}
type Target_PbTokenAuth struct {
	PbTokenAuth *Target_PacketBrokerTokenAuth `protobuf:"bytes,7,opt,name=pb_token_auth,json=pbTokenAuth,proto3,oneof" json:"pb_token_auth,omitempty"`
}

func (*Target_BasicAuth_) isTarget_DefaultAuthentication()    {}
func (*Target_CustomAuth_) isTarget_DefaultAuthentication()   {}
func (*Target_TlsClientAuth) isTarget_DefaultAuthentication() {}
func (*Target_PbTokenAuth) isTarget_DefaultAuthentication()   {}

func (m *Target) GetDefaultAuthentication() isTarget_DefaultAuthentication {
	if m != nil {
		return m.DefaultAuthentication
	}
	return nil
}

func (m *Target) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_TS002_V1_0
}

func (m *Target) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Target) GetFNsPath() string {
	if m != nil {
		return m.FNsPath
	}
	return ""
}

func (m *Target) GetSNsPath() string {
	if m != nil {
		return m.SNsPath
	}
	return ""
}

func (m *Target) GetHNsPath() string {
	if m != nil {
		return m.HNsPath
	}
	return ""
}

func (m *Target) GetRootCas() []byte {
	if m != nil {
		return m.RootCas
	}
	return nil
}

func (m *Target) GetBasicAuth() *Target_BasicAuth {
	if x, ok := m.GetDefaultAuthentication().(*Target_BasicAuth_); ok {
		return x.BasicAuth
	}
	return nil
}

func (m *Target) GetCustomAuth() *Target_CustomAuth {
	if x, ok := m.GetDefaultAuthentication().(*Target_CustomAuth_); ok {
		return x.CustomAuth
	}
	return nil
}

func (m *Target) GetTlsClientAuth() *Target_TLSClientAuth {
	if x, ok := m.GetDefaultAuthentication().(*Target_TlsClientAuth); ok {
		return x.TlsClientAuth
	}
	return nil
}

func (m *Target) GetPbTokenAuth() *Target_PacketBrokerTokenAuth {
	if x, ok := m.GetDefaultAuthentication().(*Target_PbTokenAuth); ok {
		return x.PbTokenAuth
	}
	return nil
}

func (m *Target) GetOriginNetIdAuthentication() map[uint32]*Target_Authentication {
	if m != nil {
		return m.OriginNetIdAuthentication
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Target) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Target_BasicAuth_)(nil),
		(*Target_CustomAuth_)(nil),
		(*Target_TlsClientAuth)(nil),
		(*Target_PbTokenAuth)(nil),
	}
}

type Target_BasicAuth struct {
	// Username.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Password.
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target_BasicAuth) Reset()         { *m = Target_BasicAuth{} }
func (m *Target_BasicAuth) String() string { return proto.CompactTextString(m) }
func (*Target_BasicAuth) ProtoMessage()    {}
func (*Target_BasicAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_92034e0542da6cfe, []int{0, 0}
}
func (m *Target_BasicAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target_BasicAuth.Unmarshal(m, b)
}
func (m *Target_BasicAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target_BasicAuth.Marshal(b, m, deterministic)
}
func (m *Target_BasicAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target_BasicAuth.Merge(m, src)
}
func (m *Target_BasicAuth) XXX_Size() int {
	return xxx_messageInfo_Target_BasicAuth.Size(m)
}
func (m *Target_BasicAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_Target_BasicAuth.DiscardUnknown(m)
}

var xxx_messageInfo_Target_BasicAuth proto.InternalMessageInfo

func (m *Target_BasicAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Target_BasicAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Target_CustomAuth struct {
	// Custom authorization value.
	// When using an HTTP protocol, this is used as the raw Authorization header value.
	// The value may include the authorization type (Bearer, Basic, Key, etc).
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target_CustomAuth) Reset()         { *m = Target_CustomAuth{} }
func (m *Target_CustomAuth) String() string { return proto.CompactTextString(m) }
func (*Target_CustomAuth) ProtoMessage()    {}
func (*Target_CustomAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_92034e0542da6cfe, []int{0, 1}
}
func (m *Target_CustomAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target_CustomAuth.Unmarshal(m, b)
}
func (m *Target_CustomAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target_CustomAuth.Marshal(b, m, deterministic)
}
func (m *Target_CustomAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target_CustomAuth.Merge(m, src)
}
func (m *Target_CustomAuth) XXX_Size() int {
	return xxx_messageInfo_Target_CustomAuth.Size(m)
}
func (m *Target_CustomAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_Target_CustomAuth.DiscardUnknown(m)
}

var xxx_messageInfo_Target_CustomAuth proto.InternalMessageInfo

func (m *Target_CustomAuth) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Target_TLSClientAuth struct {
	// PEM encoded client certificate.
	Cert []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	// PEM encoded private key.
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target_TLSClientAuth) Reset()         { *m = Target_TLSClientAuth{} }
func (m *Target_TLSClientAuth) String() string { return proto.CompactTextString(m) }
func (*Target_TLSClientAuth) ProtoMessage()    {}
func (*Target_TLSClientAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_92034e0542da6cfe, []int{0, 2}
}
func (m *Target_TLSClientAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target_TLSClientAuth.Unmarshal(m, b)
}
func (m *Target_TLSClientAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target_TLSClientAuth.Marshal(b, m, deterministic)
}
func (m *Target_TLSClientAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target_TLSClientAuth.Merge(m, src)
}
func (m *Target_TLSClientAuth) XXX_Size() int {
	return xxx_messageInfo_Target_TLSClientAuth.Size(m)
}
func (m *Target_TLSClientAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_Target_TLSClientAuth.DiscardUnknown(m)
}

var xxx_messageInfo_Target_TLSClientAuth proto.InternalMessageInfo

func (m *Target_TLSClientAuth) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *Target_TLSClientAuth) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Target_PacketBrokerTokenAuth struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target_PacketBrokerTokenAuth) Reset()         { *m = Target_PacketBrokerTokenAuth{} }
func (m *Target_PacketBrokerTokenAuth) String() string { return proto.CompactTextString(m) }
func (*Target_PacketBrokerTokenAuth) ProtoMessage()    {}
func (*Target_PacketBrokerTokenAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_92034e0542da6cfe, []int{0, 3}
}
func (m *Target_PacketBrokerTokenAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target_PacketBrokerTokenAuth.Unmarshal(m, b)
}
func (m *Target_PacketBrokerTokenAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target_PacketBrokerTokenAuth.Marshal(b, m, deterministic)
}
func (m *Target_PacketBrokerTokenAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target_PacketBrokerTokenAuth.Merge(m, src)
}
func (m *Target_PacketBrokerTokenAuth) XXX_Size() int {
	return xxx_messageInfo_Target_PacketBrokerTokenAuth.Size(m)
}
func (m *Target_PacketBrokerTokenAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_Target_PacketBrokerTokenAuth.DiscardUnknown(m)
}

var xxx_messageInfo_Target_PacketBrokerTokenAuth proto.InternalMessageInfo

type Target_Authentication struct {
	// Types that are valid to be assigned to Value:
	//	*Target_Authentication_BasicAuth
	//	*Target_Authentication_CustomAuth
	//	*Target_Authentication_TlsClientAuth
	//	*Target_Authentication_PbTokenAuth
	Value                isTarget_Authentication_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Target_Authentication) Reset()         { *m = Target_Authentication{} }
func (m *Target_Authentication) String() string { return proto.CompactTextString(m) }
func (*Target_Authentication) ProtoMessage()    {}
func (*Target_Authentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_92034e0542da6cfe, []int{0, 4}
}
func (m *Target_Authentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target_Authentication.Unmarshal(m, b)
}
func (m *Target_Authentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target_Authentication.Marshal(b, m, deterministic)
}
func (m *Target_Authentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target_Authentication.Merge(m, src)
}
func (m *Target_Authentication) XXX_Size() int {
	return xxx_messageInfo_Target_Authentication.Size(m)
}
func (m *Target_Authentication) XXX_DiscardUnknown() {
	xxx_messageInfo_Target_Authentication.DiscardUnknown(m)
}

var xxx_messageInfo_Target_Authentication proto.InternalMessageInfo

type isTarget_Authentication_Value interface {
	isTarget_Authentication_Value()
}

type Target_Authentication_BasicAuth struct {
	BasicAuth *Target_BasicAuth `protobuf:"bytes,1,opt,name=basic_auth,json=basicAuth,proto3,oneof" json:"basic_auth,omitempty"`
}
type Target_Authentication_CustomAuth struct {
	CustomAuth *Target_CustomAuth `protobuf:"bytes,2,opt,name=custom_auth,json=customAuth,proto3,oneof" json:"custom_auth,omitempty"`
}
type Target_Authentication_TlsClientAuth struct {
	TlsClientAuth *Target_TLSClientAuth `protobuf:"bytes,3,opt,name=tls_client_auth,json=tlsClientAuth,proto3,oneof" json:"tls_client_auth,omitempty"`
}
type Target_Authentication_PbTokenAuth struct {
	PbTokenAuth *Target_PacketBrokerTokenAuth `protobuf:"bytes,4,opt,name=pb_token_auth,json=pbTokenAuth,proto3,oneof" json:"pb_token_auth,omitempty"`
}

func (*Target_Authentication_BasicAuth) isTarget_Authentication_Value()     {}
func (*Target_Authentication_CustomAuth) isTarget_Authentication_Value()    {}
func (*Target_Authentication_TlsClientAuth) isTarget_Authentication_Value() {}
func (*Target_Authentication_PbTokenAuth) isTarget_Authentication_Value()   {}

func (m *Target_Authentication) GetValue() isTarget_Authentication_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Target_Authentication) GetBasicAuth() *Target_BasicAuth {
	if x, ok := m.GetValue().(*Target_Authentication_BasicAuth); ok {
		return x.BasicAuth
	}
	return nil
}

func (m *Target_Authentication) GetCustomAuth() *Target_CustomAuth {
	if x, ok := m.GetValue().(*Target_Authentication_CustomAuth); ok {
		return x.CustomAuth
	}
	return nil
}

func (m *Target_Authentication) GetTlsClientAuth() *Target_TLSClientAuth {
	if x, ok := m.GetValue().(*Target_Authentication_TlsClientAuth); ok {
		return x.TlsClientAuth
	}
	return nil
}

func (m *Target_Authentication) GetPbTokenAuth() *Target_PacketBrokerTokenAuth {
	if x, ok := m.GetValue().(*Target_Authentication_PbTokenAuth); ok {
		return x.PbTokenAuth
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Target_Authentication) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Target_Authentication_BasicAuth)(nil),
		(*Target_Authentication_CustomAuth)(nil),
		(*Target_Authentication_TlsClientAuth)(nil),
		(*Target_Authentication_PbTokenAuth)(nil),
	}
}

func init() {
	proto.RegisterType((*Target)(nil), "org.packetbroker.v3.Target")
	proto.RegisterMapType((map[uint32]*Target_Authentication)(nil), "org.packetbroker.v3.Target.OriginNetIdAuthenticationEntry")
	proto.RegisterType((*Target_BasicAuth)(nil), "org.packetbroker.v3.Target.BasicAuth")
	proto.RegisterType((*Target_CustomAuth)(nil), "org.packetbroker.v3.Target.CustomAuth")
	proto.RegisterType((*Target_TLSClientAuth)(nil), "org.packetbroker.v3.Target.TLSClientAuth")
	proto.RegisterType((*Target_PacketBrokerTokenAuth)(nil), "org.packetbroker.v3.Target.PacketBrokerTokenAuth")
	proto.RegisterType((*Target_Authentication)(nil), "org.packetbroker.v3.Target.Authentication")
}

func init() { proto.RegisterFile("packetbroker/api/v3/target.proto", fileDescriptor_92034e0542da6cfe) }

var fileDescriptor_92034e0542da6cfe = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x8e, 0xd2, 0x40,
	0x14, 0xc6, 0x2d, 0xec, 0x02, 0x3d, 0xc0, 0x6a, 0xc6, 0x7f, 0xdd, 0xc6, 0x3f, 0xcd, 0x26, 0x2a,
	0xeb, 0x45, 0x89, 0x10, 0x13, 0x5d, 0x6f, 0x5c, 0x88, 0xc6, 0x4d, 0xcc, 0x4a, 0xba, 0x24, 0x26,
	0xde, 0x34, 0xd3, 0x76, 0xa0, 0x0d, 0xa5, 0xd3, 0xcc, 0x4c, 0xd1, 0x8d, 0xaf, 0xe5, 0xd3, 0xf8,
	0x34, 0xa6, 0x33, 0xa5, 0x2c, 0x1b, 0xec, 0x15, 0x77, 0xfd, 0xce, 0x77, 0xce, 0x0f, 0x66, 0xce,
	0xd7, 0x82, 0x95, 0x62, 0x7f, 0x41, 0x84, 0xc7, 0xe8, 0x82, 0xb0, 0x3e, 0x4e, 0xa3, 0xfe, 0x6a,
	0xd8, 0x17, 0x98, 0xcd, 0x89, 0xb0, 0x53, 0x46, 0x05, 0x45, 0xf7, 0x29, 0x9b, 0xdb, 0x37, 0xbb,
	0xec, 0xd5, 0xd0, 0x7c, 0xbe, 0x6b, 0x8c, 0x24, 0xd9, 0x92, 0xab, 0xa9, 0x93, 0x3f, 0x00, 0x8d,
	0xa9, 0xc4, 0xa0, 0xf7, 0xd0, 0x92, 0x35, 0x9f, 0xc6, 0x86, 0x66, 0x69, 0xbd, 0xa3, 0xc1, 0x53,
	0x7b, 0x07, 0xd3, 0x9e, 0x14, 0x4d, 0x4e, 0xd9, 0x8e, 0x0c, 0x68, 0xe2, 0x20, 0x60, 0x84, 0x73,
	0xa3, 0x66, 0x69, 0x3d, 0xdd, 0x59, 0x4b, 0x64, 0x82, 0x3e, 0x73, 0x13, 0xee, 0xa6, 0x58, 0x84,
	0x86, 0xae, 0xbc, 0xd9, 0x25, 0x9f, 0x60, 0x11, 0xe6, 0x1e, 0x2f, 0x3d, 0x50, 0x1e, 0xdf, 0x78,
	0x61, 0xe9, 0xb5, 0x95, 0x17, 0x16, 0xde, 0x31, 0xb4, 0x18, 0xa5, 0xc2, 0xf5, 0x31, 0x37, 0x1a,
	0x96, 0xd6, 0xeb, 0x38, 0xcd, 0x5c, 0x8f, 0x31, 0x47, 0x9f, 0x01, 0x3c, 0xcc, 0x23, 0xdf, 0xc5,
	0x99, 0x08, 0x8d, 0xba, 0xa5, 0xf5, 0xda, 0x83, 0x17, 0x3b, 0x4f, 0xa1, 0x0e, 0x6d, 0x8f, 0xf2,
	0xee, 0xf3, 0x4c, 0x84, 0x5f, 0xee, 0x38, 0xba, 0xb7, 0x16, 0xe8, 0x02, 0xda, 0x7e, 0xc6, 0x05,
	0x5d, 0x2a, 0xd0, 0x81, 0x04, 0xbd, 0xac, 0x02, 0x8d, 0x65, 0x7b, 0x41, 0x02, 0xbf, 0x54, 0xe8,
	0x0a, 0xee, 0x8a, 0x98, 0xbb, 0x7e, 0x1c, 0x91, 0x44, 0x28, 0xdc, 0xa1, 0xc4, 0x9d, 0x56, 0xe1,
	0xa6, 0x5f, 0xaf, 0xc6, 0x72, 0xa2, 0x20, 0x76, 0x45, 0xcc, 0x37, 0x05, 0xf4, 0x1d, 0xba, 0xa9,
	0xe7, 0x0a, 0xba, 0x20, 0x89, 0x42, 0x36, 0x25, 0xf2, 0x4d, 0x15, 0x72, 0x22, 0xcb, 0x23, 0x59,
	0x9e, 0xe6, 0x93, 0x05, 0xba, 0x9d, 0x7a, 0xa5, 0x44, 0xbf, 0xe1, 0x09, 0x65, 0xd1, 0x3c, 0x4a,
	0xdc, 0x84, 0x08, 0x37, 0x0a, 0x24, 0x9d, 0x24, 0x22, 0xf2, 0xb1, 0x88, 0x68, 0x62, 0xb4, 0xac,
	0x7a, 0xaf, 0x3d, 0x38, 0xab, 0xfa, 0x9d, 0x6f, 0x72, 0xfe, 0x92, 0x88, 0x8b, 0xe0, 0x7c, 0x6b,
	0xf8, 0x53, 0x22, 0xd8, 0xb5, 0x73, 0x4c, 0xff, 0xe7, 0x9b, 0x63, 0xd0, 0xcb, 0x7d, 0x20, 0x13,
	0x5a, 0x19, 0x27, 0x2c, 0xc1, 0x4b, 0x22, 0xe3, 0xa8, 0x3b, 0xa5, 0xce, 0xbd, 0x14, 0x73, 0xfe,
	0x93, 0xb2, 0xa0, 0x08, 0x5c, 0xa9, 0xcd, 0x13, 0x80, 0xcd, 0x2e, 0xd0, 0x03, 0x38, 0x5c, 0xe1,
	0x38, 0x5b, 0x23, 0x94, 0x30, 0xdf, 0x42, 0x77, 0xeb, 0x82, 0x11, 0x82, 0x03, 0x9f, 0x30, 0x21,
	0xbb, 0x3a, 0x8e, 0x7c, 0x46, 0xf7, 0xa0, 0xbe, 0x20, 0xd7, 0x92, 0xdf, 0x71, 0xf2, 0x47, 0xf3,
	0x31, 0x3c, 0xdc, 0x79, 0x89, 0xe6, 0xdf, 0x1a, 0x1c, 0x6d, 0x9f, 0xe5, 0x56, 0x12, 0xb5, 0x7d,
	0x25, 0xb1, 0xb6, 0xdf, 0x24, 0xd6, 0xf7, 0x9f, 0xc4, 0x83, 0xfd, 0x24, 0x71, 0xd4, 0x2c, 0x36,
	0x67, 0xfe, 0x82, 0x67, 0xd5, 0x91, 0x5a, 0x6f, 0x2a, 0xbf, 0xe4, 0xae, 0xdc, 0x14, 0xfa, 0xb8,
	0x5e, 0xbb, 0xba, 0xaf, 0xd7, 0x55, 0xff, 0x66, 0x9b, 0x58, 0x44, 0xe4, 0xac, 0xf6, 0x4e, 0x1b,
	0x19, 0xf0, 0x28, 0x20, 0x33, 0x9c, 0xc5, 0xe2, 0xd6, 0x6b, 0x30, 0x3a, 0xfd, 0xf1, 0x6a, 0x4e,
	0xb7, 0x81, 0x94, 0xcd, 0x8b, 0x0f, 0xec, 0x87, 0x9b, 0x75, 0xaf, 0x21, 0xbf, 0x92, 0xc3, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0x1e, 0x49, 0x4e, 0xc2, 0x05, 0x00, 0x00,
}
